config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  authenticated :user do
    root 'products#index', as: :authenticated_root
  end

  root "application#landing"

  resources :products
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
  has_one_attached :picture
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: :landing

  def landing
    @products = Product.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(object_params)
    @product.save
    redirect_to products_path
  end

  def show
    @product = Product.find(params[:id])
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(object_params)
    redirect_to product_path(@product)
  end

  private

  def object_params
    params.require(:product).permit(:description, :quantity, :price, :name,
                                   :picture)  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/landing.html.erb
<div class="jumbotron">
  <h1 class="display-4">Mi tienda en línea</h1>
  <hr class="my-4">
  <p class="lead">
    <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'btn btn-primary btn-lg' %>
  </p>
</div>
<div class='container'>
  <div class='row'>
    <div class='col-sm-12'>
      <h2>Productos</h2>
    </div>

    <% @products.each do |product| %>
      <div class='col-sm-12 col-lg-3 col-md-4'>
        <div class="card w-100">
          <% if product.picture.attached? %>
            <%= image_tag product.picture, class: 'card-img-top', alt: product.name %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= product.name %></h5>
            <p class="card-text"><%= product.description %>
            <p class='badge badge-primary float-right'><%= number_to_currency(product.price) %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inventory</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <% if user_signed_in? %>
        <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete %>
        <%= link_to 'Usuarios', users_path %>
        <%= link_to 'Productos', products_path %>
      <% end %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/edit.html.erb
<%= form_for @product do |f|%>
    Nombre: <%= f.text_field :name %>
    Descripción: <%= f.text_field :description %>
    Cantidad: <%= f.number_field :quantity %>
    Precio: <%= f.number_field :price %>
    Imagen: <%= f.file_field :picture %>
    <%= f.submit 'Guardar'  %>
<% end %>

app/views/products/index.html.erb
<div>
  <%= link_to 'Agregar Producto', new_product_path %>
</div>

<table>
  <thead>
    <th>Nombre</th>
    <th>Cantidad</th>
    <th>Descripción</th>
    <th>Precio</th>
    <th>Detalle</th>
  </thead>
  <tbody>
    <% @products.each do |p| %>
      <tr>
        <td><%= p.name %></td>
        <td><%= p.quantity %></td>
        <td><%= p.description %></td>
        <td><%= p.price %></td>
        <td><%= link_to 'Detalle', product_path(p) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/products/new.html.erb
<%= form_for @product do |f|%>
    Nombre: <%= f.text_field :name %>
    Descripción: <%= f.text_field :description %>
    Cantidad: <%= f.number_field :quantity %>
    Precio: <%= f.number_field :price %>
    Imagen: <%= f.file_field :picture %>
    <%= f.submit 'Guardar'  %>
<% end %>

app/views/products/show.html.erb
<h1>Detalle de producto</h1>
<div>
  <label>Nombre:</label>
  <strong><%= @product.name %></strong>
</div>
<div>
  <label>Descripción:</label>
  <strong><%= @product.description %></strong>
</div>
<div>
  <label>Cantidad:</label>
  <strong><%= @product.quantity %></strong>
</div>
<div>
  <label>Precio:</label>
  <strong><%= @product.price %></strong>
</div>
<div>
  <%= link_to 'Editar', edit_product_path(@product) %>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>